name: ML Pipeline CI

on:
  push:
    paths:
      - '**.py'
      - 'requirements.txt'
      - 'Makefile'
      - 'data/raw/*'
  pull_request:
    paths:
      - '**.py'
      - 'requirements.txt'
      - 'Makefile'
      - 'data/raw/*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint code
      run: |
        source venv/bin/activate
        flake8 .
        pylint main.py model_pipeline.py

    - name: Run tests
      run: |
        source venv/bin/activate
        pytest || echo "No tests found."

    - name: Run pipeline prepare
      run: |
        source venv/bin/activate
        python main.py --prepare --data data/raw/creditcard.csv || echo "Data may be missing, skipping."

    - name: Train model
      run: |
        source venv/bin/activate
        python main.py --train --model-type random_forest --model-name github_ci_model || echo "Data may be missing, skipping training."

    - name: Evaluate model
      run: |
        source venv/bin/activate
        python main.py --evaluate --model-name github_ci_model || echo "Data may be missing, skipping evaluation."
